[phases.setup]
aptPkgs = []
nixPkgs = ["hugo", "caddy"]

[phases.build]
cmds = ["hugo --minify"]  

[environment]
HUGO_VERSION = "v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended" 

[[nixpacks.included_files]]
paths = ["/public"]  
